language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - yarn install
services:
  - postgresql

env:
  global:
  - NODE_ENV=test

before_script:
  - psql -c 'create database book_test;' -U postgres
  - psql -c "CREATE USER femi WITH PASSWORD null;" -U postgres
  - npm run build
  - npm install -g sequelize-cli
  - sequelize db:migrate
script:
  - yarn run test

after_success:
  - yarn run coverage